// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2025-07-15",
  devtools: { enabled: true },
  nitro: {
    // Cloudflare Workers 部署：固定为 cloudflare 以生成正确的运行时与静态资源处理
    preset: "cloudflare",
  },
  runtimeConfig: {
    // server-only
    defaultChannels: [
      "tgsearchers3",
      "yunpanxunlei",
      "tianyifc",
      "BaiduCloudDisk",
      "txtyzy",
      "peccxinpd",
      "gotopan",
      "xingqiump4",
      "yunpanqk",
      "PanjClub",
      "kkxlzy",
      "baicaoZY",
      "MCPH01",
      "share_aliyun",
      "bdwpzhpd",
      "ysxb48",
      "jdjdn1111",
      "yggpan",
      "MCPH086",
      "zaihuayun",
      "Q66Share",
      "NewAliPan",
      "ypquark",
      "Oscar_4Kmovies",
      "ucwpzy",
      "alyp_TV",
      "alyp_4K_Movies",
      "shareAliyun",
      "alyp_1",
      "dianyingshare",
      "Quark_Movies",
      "XiangxiuNBB",
      "NewQuark",
      "ydypzyfx",
      "kuakeyun",
      "ucquark",
      "xx123pan",
      "yingshifenxiang123",
      "zyfb123",
      "tyypzhpd",
      "tianyirigeng",
      "cloudtianyi",
      "hdhhd21",
      "Lsp115",
      "oneonefivewpfx",
      "Maidanglaocom",
      "qixingzhenren",
      "taoxgzy",
      "tgsearchers115",
      "Channel_Shares_115",
      "tyysypzypd",
      "vip115hot",
      "wp123zy",
      "yunpan139",
      "yunpan189",
      "yunpanuc",
      "yydf_hzl",
      "alyp_Animation",
      "alyp_JLP",
      "leoziyuan",
    ],
    defaultConcurrency: 10,
    pluginTimeoutMs: 15000,
    cacheEnabled: true,
    cacheTtlMinutes: 30,
    public: {
      apiBase: "/api",
    },
  },
});
